spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: planning
      uri: ${MONGO_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}
  rabbitmq:
    host: rabbitmq
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

server:
  port: 8080

custom-properties:
  allowed-origin: ${SIMPLE_BILLS_GUI_URL}
  expense-categories:
    - food
    - travel
    - education
    - fun
    - utility
    - health
    - insurance
    - car
    - public transport
    - sport
    - electronics
    - garden
  income-categories:
    - salary