services:

  simple-bills:
    build: 
      context: simple-bills-gui
      dockerfile: DockerfileLocal
    ports:
      - 80:80
    depends_on:
      - transaction-management
      - planning
      - asset-management

  transaction-management:
    build: transaction-management
    restart: unless-stopped
    depends_on:
      - rabbitmq
    ports:
      - 8081:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - common_env_local.env

  planning:
    build: planning
    restart: unless-stopped
    depends_on:
      - rabbitmq
    ports:
      - 8082:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - common_env_local.env

  asset-management:
    build: asset-management
    restart: unless-stopped
    depends_on:
      - rabbitmq
    ports:
      - 8083:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - common_env_local.env

  mongodb:
    image: mongo:4.4.16
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

volumes:
  mongo_data:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local
  postgres_data:
    driver: local
  