spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: asset
      uri: ${MONGO_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}
  rabbitmq:
    host: rabbitmq
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

server:
  port: 8080

custom-properties:
  allowed-origin: ${SIMPLE_BILLS_GUI_URL}
  transaction-url: ${TRANSACTION_URL}
  planning-url: ${PLANNING_URL}